apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: contribskopeoimagestable-skopeo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: contribskopeoimagestable-skopeo
    app.kubernetes.io/part-of: skopeo
  name: contribskopeoimagestable-skopeo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: contribskopeoimagestable-skopeo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: contribskopeoimagestable-skopeo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/lmandvek-tenant/skopeo/contribskopeoimagestable-skopeo@sha256:678f41f975bcdc3d4a3048c8ceca0f5d017f51b302fa84100a1b4fdbd592d356
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
